### ISSUE TITLE
Telnet overbufferflow test fails locally

### ISSUE THREAD

**Issue by redragonx** [redragonx/SuperHoneyPot#105]

**Comment by raddack** [comment]
I have this fixed this on UnitTest branch. I cant push to the branch.  It appears I don't have access to modify the repository anymore.

![capture](https://cloud.githubusercontent.com/assets/2530959/14585529/9792f342-0436-11e6-9cac-500981e0d0bf.PNG)

**Comment by fred15** [comment]
this done now?
