### ISSUE TITLE
fix(?) sshing from putty

### ISSUE THREAD

**Issue by redragonx** [redragonx/SuperHoneyPot#50]
We should check this out. @auroraaxela

**Comment by auroraaxela** [comment]
I'll take a look. Known issues?

**Comment by mbatkali** [comment]
Where are you SSHing to?

**Comment by redragonx** [comment]
None, I think it just needs to be tested. @fred15 can confirm this

**Comment by fred15** [comment]
the ssh_plugin needs to be fixed when you try to ssh into it from putty mike. I gotta look at that eventually

**Comment by auroraaxela** [comment]
I have found two issues so far with using putty. I am isolating and working on fixes. Attacks currently are being logged and sent to the database, but no information is getting through due to the early closure of the session.

**Comment by redragonx** [comment]
Closing for now. No hacker uses putty ;)
