### ISSUE TITLE
Fix telnet_reader plugin to work with Windows

### ISSUE THREAD

**Issue by mbatkali** [redragonx/SuperHoneyPot#63]
Fix telnet_reader to work with Windows and Ubuntu. Ubuntu works fine, Windows output causes issues.

**Comment by fred15** [comment]
yes yes I gotta work on them to all work on windows, I got it lol, I've fixed some of the issues but that was before I had my vm all set up

**Comment by fred15** [comment]
hey, this actually works perfectly on my computer, the program might run different if its ran on windows. I run it on my VM and connect via windows and it works perfectly fine.
