### ISSUE TITLE
Move configuration items to separate config file.

### ISSUE THREAD

**Issue by auroraaxela** [redragonx/SuperHoneyPot#65]
This file should be separate and easily modifiable for the user to input setup items like database location and account info, so that each piece of the program does not need to be changed.

**Comment by redragonx** [comment]
oh now you listen to me :+1:

**Comment by fred15** [comment]
lol this shouldnt be too hard, just create a few text files on a seperate dir which then we can modify easily and import where we need them

**Comment by auroraaxela** [comment]
I think we can accomplish it with a single file

**Comment by redragonx** [comment]
put it with the loader directory

**Comment by auroraaxela** [comment]
that's the plan

**Comment by redragonx** [comment]
Are we happy with the current config?

**Comment by redragonx** [comment]
Closing for now,
