### ISSUE TITLE
add linux distro detection

### ISSUE THREAD

**Issue by redragonx** [redragonx/SuperHoneyPot#75]
Since this will be mainly for Linux and to handle edge cases in some of our code, we'll need to implement this in some form. And there's no magical command that works on all distros.

Ideally, we would only need to run `lsb_release -a` and it'll tell us everything but not every distro has this command, so we will find specific distro files. Which are listed here. http://unix.stackexchange.com/questions/35183/how-do-i-identify-which-linux-distro-is-running

`lsb release example for arch`

> LSB Version:  1.4
> Distributor ID: Arch
> Description:    Arch Linux
> Release:    rolling
> Codename:   n/a

**Comment by fred15** [comment]
done i hope, stephen needs to check it out
