### ISSUE TITLE
Handle possible lost of database connection

### ISSUE THREAD

**Issue by redragonx** [redragonx/SuperHoneyPot#82]
So far, the program will continue without errors. 
- Should it try 3 times before giving up? 
- Should we have a buffered or backlog of some type?
- Should it exit upon losing a connection?

**Comment by redragonx** [comment]
Your thoughts @auroraaxela ?

**Comment by auroraaxela** [comment]
What happens currently if the DB can't be reached?

**Comment by mbatkali** [comment]
I will work on this so that the loader will show a failed connection // print any response from the database.

**Comment by auroraaxela** [comment]
I am planning to work on an automation script that will attempt reconnection or even restart upon detecting failure.

**Comment by auroraaxela** [comment]
Connection loss handled, see issue #91.
