### ISSUE TITLE
Telnet BufferOverflow

### ISSUE THREAD

**Issue by raddack** [redragonx/SuperHoneyPot#92]
![failure](https://cloud.githubusercontent.com/assets/2530959/14376048/67908386-fd23-11e5-91cc-93e3e78d945f.PNG)
If the client sends more then 16793598 bytes then then the telnet thread will stall and will not timeout.

Please look at test_bufferoverflow in telnet_reader_test on Unittest.

**Comment by redragonx** [comment]
I think by design, @fred15 only allowed the plugin to store so much. Do we want to fix?

**Comment by fred15** [comment]
I only allowed it 128 bytes I'll look into this, I think I may have not done so for the login and password... I think I did but who knows
