### ISSUE TITLE
Catch Failure to Setup Port, and Incorporate into Handling Closure

### ISSUE THREAD

**Issue by WDKing** [redragonx/SuperHoneyPot#98]
When a port fails to open, catch the issue in the loader and integrate this into not adding that port into the list of ports that must be closed upon closure of the program.

**Comment by redragonx** [comment]
Fixeed

**Comment by auroraaxela** [comment]
Issue remains, if port is already in use, the loader will still try to close the port on system exit and hangs.

**Comment by fred15** [comment]
Yep, I'll look into it in the morning, seemed to be totally fine on Thursday finally but okay

**Comment by auroraaxela** [comment]
It looks like it is not trying to open the port if it is in use, so that is ok. But it still tries to close it.

**Comment by fred15** [comment]
It doesn't actually close it though,  it's just closing that thread

**Comment by fred15** [comment]
If we closed that thread it'd fail trying to close it from loader, I could make a boolean for different closes, one just kills the thread, the other one closes the servers and connections, no issue

**Comment by fred15** [comment]
so this is done, as soon as someone finishes the fix on the permission issues me and @raddack  are having pushing then it should be fixed
